apiVersion: gateway.kyma-project.io/v1alpha2
kind: Api
metadata:
    name: {{ .Release.Name }}
spec:
    service:
      name: {{ .Release.Name }}
      port: {{ .Values.service.port }}
    hostname: githubconnector.{{ .Values.kymaAddress }}