replicaCount: 1

container:
  image: kymaflyingseals/slack-connector:0.0.4

  containerPort: 8080
  limits:
    memory: "128Mi"
    cpu: "100m"

service:
  port: 80

kymaAddress: 35.195.198.66.xip.io
slackBotToken: {token}