apiVersion: applicationconnector.kyma-project.io/v1alpha1
kind: Application
metadata:
  name: {{ include "slack-connector-chart.release.name" . }}-app
  labels:
    app: {{ include "slack-connector-chart.name" . }}
    app.kubernetes.io/name: {{ template "slack-connector-chart.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" | trimSuffix "-" }}
    app.kubernetes.io/managed-by: {{ .Release.Service | trimSuffix "-"  }}
    app.kubernetes.io/instance: {{ .Release.Name | trimSuffix "-" }}

spec:
  description: {{ .Chart.Description }}
