apiVersion: applicationconnector.kyma-project.io/v1alpha1
kind: Application
metadata:
  name: {{ include "slack-connector-chart.release.name" . }}-app
  labels:
    app: {{ include "slack-connector-chart.name" . }}
    app.kubernetes.io/name: {{ template "slack-connector-chart.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}

spec:
  description: {{ .Chart.Description }}
