kind: Service
apiVersion: v1
metadata:
  name: {{ include "slack-connector-chart.release.name" . }}
  labels:
    app: {{ include "slack-connector-chart.name" . }}
    app.kubernetes.io/name: {{ template "slack-connector-chart.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" | trimSuffix "-" }}
    app.kubernetes.io/managed-by: {{ .Release.Service | trimSuffix "-" }}
    app.kubernetes.io/instance: {{ .Release.Name | trimSuffix "-" }}

spec:
  selector:
    app: {{ include "slack-connector-chart.name" . }}
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.containerPort }}
