// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import json "encoding/json"
import mock "github.com/stretchr/testify/mock"

// Sender is an autogenerated mock type for the Sender type
type Sender struct {
	mock.Mock
}

// SendToKyma provides a mock function with given fields: eventType, eventTypeVersion, eventID, sourceID, data
func (_m *Sender) SendToKyma(eventType string, eventTypeVersion string, eventID string, sourceID string, data json.RawMessage) error {
	ret := _m.Called(eventType, eventTypeVersion, eventID, sourceID, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, string, json.RawMessage) error); ok {
		r0 = rf(eventType, eventTypeVersion, eventID, sourceID, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
