name: azure-comments-analytics
version: 1.0.0
id: f906c336-ed1f-45cc-8676-ef710e3cef89
displayName: "Azure Comments Analytics Scenario"
description: "Allows you to install Team Hack showcase scenario"

tags: github, slack, azure, example
providerDisplayName: Kyma
longDescription: "This addon analyzes new issues on connected GitHub repository and sends notifications to proper Slack channel if issue needs a review."
imageURL: https://github.com/pPrecel/hack-showcase/raw/master/logo.png
documentationURL: https://github.com/kyma-incubator/hack-showcase/tree/master/docs
