name: github-issue-sentiment-analysis
version: 1.0.0
id: f906c336-ed1f-45cc-8676-ef710e3cef89
displayName: "GitHub Issue Sentiment Analysis"
description: "Allows you to install Team Hack showcase scenario"

tags: github, slack, azure, example
providerDisplayName: Kyma
longDescription: "This add-on analyzes new issues on connected GitHub repository and, if issue needs a review, sends notifications to proper Slack channel."
imageURL: https://github.com/kyma-incubator/github-slack-connectors/blob/master/logo.png
documentationURL: https://github.com/kyma-incubator/github-slack-connectors/tree/master/docs
