apiVersion: applicationconnector.kyma-project.io/v1alpha1
kind: Application
metadata:
  name: {{ include "release.name" }}-app
  labels:
    app: {{ include "github-connector-chart.name" . }}
    chart: {{ include "github-connector-chart.chart" . }}
    release: {{ include "release.name" }}
    heritage: {{ include "release.service" }}
spec:
  description: {{ .Chart.Description }}
