apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "release.name" }}
  labels:
    app: {{ include "github-connector-chart.name" . }}
    chart: {{ include "github-connector-chart.chart" . }}
    release: {{ include "release.name" }}
    heritage: {{ include "release.service" }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "release.name" }}
  template:
    metadata:
      labels:
        app: {{ include "release.name" }}
    spec:
      containers:
      - name: main
        image: {{ .Values.image }}
        resources:
          limits:
            memory: {{ .Values.container.limits.memory }}
            cpu: {{ .Values.container.limits.cpu }}
        ports:
        - containerPort: {{ .Values.container.containerPort }}
        env:
        - name: PORT
          value: {{ quote .Values.container.containerPort }}
        - name: GITHUB_CONNECTOR_NAME
          value: {{ include "release.name" }}

