kind: Service
apiVersion: v1
metadata:
  name: {{ include "release.name" }}
  labels:
    app: {{ include "github-connector-chart.name" . }}
    chart: {{ include "github-connector-chart.chart" . }}
    release: {{ include "release.name" }}
    heritage: {{ include "release.service" }}
spec:
  selector:
    app: {{ include "release.name" }}
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.containerPort }}
