apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-serviceinstances
  namespace: julia3
subjects:
- kind: ServiceAccount
  name: default
  namespace: julia3
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: serviceinstance-reader # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io