apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-read-pods
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: {{ .Release.Name }}-pod-reader # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io