replicaCount: 1

container:
  image: kymaflyingseals/github-connector:0.3.2
  containerPort: 8080
  limits:
    memory: "128Mi"
    cpu: "500m"

service:
  port: 80

kymaAddress: 35.195.198.66.xip.io

githubToken: sampleToken
githubEndpoint: 
  - repo
  - repo2