apiVersion: applicationconnector.kyma-project.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ include "slackconnector.name" . }}
    app.kubernetes.io/name: {{ template "slackconnector.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}

spec:
  description: {{ .Chart.Description }}
