apiVersion: applicationconnector.kyma-project.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}-app
  labels:
    app: {{ include "slackconnector.name" . }}
    chart: {{ include "slackconnector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/name: {{ template "slackconnector.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}


spec:
  description: {{ .Chart.Description }}
