name: slack-connector
version: 0.1.0
id: 7629244a-98bb-4cb8-a2b0-5f5527c8ecaa
displayName: "Slack Connector"
description: "Allows communication with Slack using Slack Web API."

tags: slack
providerDisplayName: Kyma
longDescription: "Allows communication with Slack using Slack Web API."
imageURL: https://cdn.brandfolder.io/5H442O3W/as/pl546j-7le8zk-199wkt/Slack_Mark.svg?width=256&height=256
documentationURL: https://github.com/kyma-incubator/hack-showcase/tree/master/docs/slack-connector